apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  labels:
    app: ardortrip
type: Opaque
stringData:
  # Demo / Local development placeholder credentials
  DB_USER: "ardor_user"
  DB_PASSWORD: "demo_ardor_secure_pass"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
